# Google Cloud Build configuration for Flight Delay Prediction API
#
# This file defines the CI/CD pipeline for building and deploying
# the application to Google Cloud Run.
#
# Substitutions:
#   _SERVICE_NAME: Name of the Cloud Run service (default: delay-api)
#   _REGION: GCP region for deployment (default: us-central1)
#   _MEMORY: Memory allocation (default: 2Gi)
#   _CPU: CPU allocation (default: 2)

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$BUILD_ID'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
      - '.'
    timeout: '600s'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=300'
      - '--concurrency=80'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=8000'
    waitFor: ['push-image']

  # Step 4: Set IAM policy for public access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'set-iam-policy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '${_SERVICE_NAME}'
      - '--region=${_REGION}'
      - '--member=allUsers'
      - '--role=roles/run.invoker'
    waitFor: ['deploy-cloud-run']

  # Step 5: Run smoke tests
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'smoke-test-health'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the service URL
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "Testing health endpoint: $$SERVICE_URL/health"

        # Test health endpoint
        RESPONSE=$$(curl -s -o /dev/null -w "%{http_code}" $$SERVICE_URL/health)

        if [ "$$RESPONSE" = "200" ]; then
          echo "✓ Health check passed"
        else
          echo "✗ Health check failed with status $$RESPONSE"
          exit 1
        fi
    waitFor: ['set-iam-policy']

  # Step 6: Run prediction test
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'smoke-test-predict'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the service URL
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "Testing predict endpoint: $$SERVICE_URL/predict"

        # Test predict endpoint
        RESPONSE=$$(curl -s -X POST "$$SERVICE_URL/predict" \
          -H "Content-Type: application/json" \
          -d '{
            "flights": [
              {
                "OPERA": "Aerolineas Argentinas",
                "TIPOVUELO": "N",
                "MES": 3
              }
            ]
          }')

        echo "Response: $$RESPONSE"

        # Check if response contains "predict" field
        if echo "$$RESPONSE" | grep -q '"predict"'; then
          echo "✓ Prediction test passed"
        else
          echo "✗ Prediction test failed"
          exit 1
        fi
    waitFor: ['smoke-test-health']

# Configuration options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build
timeout: '1200s'

# Default substitutions
substitutions:
  _SERVICE_NAME: 'delay-api'
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY_REPO: 'cloud-run-images'
  _MEMORY: '2Gi'
  _CPU: '2'

# Images to store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
